---
title: "Creative Coding with Twine"
---

View slideshow: [Twine slides](/slides.md)

## How To

Use this guide to make a few basic customizations. There are many more you can find in the [Harlowe Documentation](https://twine2.neocities.org/) and the [Twine Cookbook](https://twinery.org/cookbook/).

### Link between passages

- Link syntax uses double brackets: `[[passage name]]` 

- If you want to display text other than the passage name: `[[continue your adventure|passage name]]`

### Style your text

Harlowe uses macros to style text, following this basic syntax:

```markdown
(text-style:"fade-in-out")[This text blinks]

(color:pink)[This text is pink]

(text-rotate-z:90)[This text is rotated 90 degrees]

(bg:green)[This text has a green background]

(color:green)+(font:"courier")[This text has two style macros applied]
```

For style that will refer to the entire passage, use an open bracket at the end:

```markdown
(color:cyan)[=
    The rest of the passage will be cyan

```

You can also style the entire page using "enchant" macros:

`(enchant:?page,(bg:lime))`

### Hide and show content

- Link macros can create clickable text that gets replaced by other text
  `(link:"Click me to reveal")[This text is revealed]`
- You can display another passage within a passage (useful if you want to repeat bits of code): `(show:"passage")`
- To go to another passage: `(go-to:"passage")`
- To display text after a delay:
  `(after:1s)[Wait one second before displaying this]`
- You can create a passage that unveils slowly by embedding choices within choices:

```markdown
You are going down (link: "a passageway")[an extremely long passageway]
Do you want to turn left?
(link:"yes, let's turn left")[You turn left and the hallway goes on (link:"forever")[for what feels like forever]
Next you have the option to go (link:"right")[right, 
which you take, and then you find yourself at another (link: "fork")[fork. 
Do you go left or right?
(link:"Left")[You've reached a dead end.]
(link:"Right")[You've reached your destination!]]]]
```

- You can also create a pop-up that will display before page content:
`(dialog:[Welcome to my game!],"OK")`

### Introduce variety

- Use 'either' to randomly select a value from a list:
`The sky is (either:"blue", "pink", "orange", "green")`

- Use 'random' to generate random numbers:
`Rolling six-sided die: (random: 1,6)`

### Set and change variables

- To set a variable: `(set: $name to "Alice")`

- To display a variable: `Hello, $name`

- You can also get user input and store it in a variable:
`What's your name? (input:2bind $name,"X","")`

- Variables can also hold numbers:
`(set: $score to 1)`

- And you can do math on them:
`(set: $score to it + 1)`

### Use conditionals

Conditional syntax can use variables to introduce game-like elements,

``` html
(if: $score > 10)[You win!!]
(else:)[You lose.]
```

``` html
(if: $door is "locked")[Sorry, the door is locked]
(else:)[(go-to:"door")]
```

### Navigation

To include some text or code on every page, create a passage and give it the "header" tag. It will automatically appear at the beginning of each passage. You can also use the "footer" tag to put it at the end of each passage.

Because Twine is designed for games, there isn't much built-in navigation. It can be helpful to use a header or footer to link to a page with more navigation links or guides if a player gets lost.


## Resources

### Twine tutorials

- [Twine Cookbook]([https://twinery.org/cookbook/](https://twinery.org/cookbook/))
- [Harlowe documentation](https://twine2.neocities.org/) - this is the standard story template
- [Twine and Interactive Fiction Handbook (slides)](https://docs.google.com/presentation/d/1bNzxW39pYul2yVieuxaSsnB5SAexOde1Higr9mxs7EA/edit)
- [Programming Historian: Interactive Text Games Using Twine](https://programminghistorian.org/en/lessons/interactive-text-games-using-twine)


### Examples

- [Open Sorcery](https://abigailcorfman.com/Home/OpenSorcery) and its sequel [Open Sorcery Sea++](https://opensorcerygames.itch.io/open-sorcery-sea)
- [16 Ways to Kill a Vampire at McDonalds](https://abigailcorfman.com/Home/Vampire)
- [Digital Scholarship Adventure Game](https://digitalscholarship.brynmawr.edu/game/)
- [Critters](https://alicetmcgrath.com/fun/) (a short and goofy game for this workshop)

### Other tools for Creative Coding
- Inform7
- Texture
- Hosted Games
- Other options here: [Tools and Resources for Making Games](https://docs.google.com/document/d/1vIRlYDjwK7E8XufV5Cr0gYtmAvd0gWRORHF23JX28Ek/edit?tab=t.0)